export const ADD_CONTACT="ADD_CONTACT";
export const REMOVE_CONTACT="REMOVE_CONTACT";

export const CONTACT_REQUEST='CONTACT_REQUEST';
export const CONTACT_SUCCESS='CONTACT_SUCCESS';
export const CONTACT_FAILURE='CONTACT_FAILURE';
export const INIT_CONTACT='INIT_CONTACT';

export const ADD_ACCOUNT="ADD_ACCOUNT";
export const REMOVE_ACCOUNT="REMOVE_ACCOUNT";

export const ACCOUNT_REQUEST='ACCOUNT_REQUEST';
export const ACCOUNT_SUCCESS='ACCOUNT_SUCCESS';
export const ACCOUNT_FAILURE='ACCOUNT_FAILURE';
export const INIT_ACCOUNT='INIT_ACCOUNT';

export const AUTH_REQUEST="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILURE";
export const AUTH_LOGOUT="AUTH_LOGOUT";